### ISSUE TITLE
OMEMO not sending "long" messages

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#56]
## Bevor you create a new issue:

```
- [ X ] I searched for similar issues and did not find one
- [ X ] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

- Bug report (I searched for similar issues and did not find one)
 

## Current behavior:
If you try to send longer OMEMO encrypted messages they stay in the sending state and never actually get send.

**Logs:**
```
Error during message parsing.System.Xml.XmlException: '', hexadecimal value 0x15, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at XMPP_API.Classes.Network.XML.MessageParser2.parseToXmlNodes(String& msg)
   at XMPP_API.Classes.Network.XML.MessageParser2.parseMessageInternal(String& msg)
   at XMPP_API.Classes.Network.XML.MessageParser2.parseMessages(String& msg)
   at XMPP_API.Classes.Network.XMPPConnection2.<parseMessageAsync>d__62.MoveNext()
```

## Expected behavior:
Send long OMEMO encrypted messages.

## Minimal reproduction of the problem with instructions:
Send for example:
```
Lorem ipsum dolor sit amet consectetur adipiscing elit curabitur, a maecenas morbi sodales convallis urna iaculis dui vel, risus accumsan quam odio cubilia integer molestie. Pharetra donec blandit euismod purus aliquam libero dignissim et semper, tempus phasellus volutpat arcu est odio fusce rutrum eu, nulla convallis ad ac laoreet pretium sociosqu tortor. Sagittis bibendum nibh eget tempus integer fermentum interdum molestie taciti sem elementum nisi, gravida et cum hac fusce pharetra potenti a blandit varius maecenas, netus laoreet nam lectus vel praesent vitae urna aenean risus natoque.
```

## Environment:

```
App Version(s): 
v.0.12.0.0

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [ X ] Desktop
- [ X ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [ X ] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
This issue is caused by:
https://github.com/UWPX/UWPX-Client/blob/cdd26c915d6ca80dd7d69079cce34e865f85e1fd/AES_GCM/AesGcmWrapper.cpp#L8

It does not return for inputs greater than 255 bytes.

**Comment by COM8** [comment]
https://github.com/openluopworld/aes_gcm/issues/1
